---
title: "HW2"
author: "MariaRomanova"
output: pdf_document
---

```{r}
library("datasets")
data = Orange
```


```{r}
work_with_dataset <- function(data, rows, columns, operation) {
  subsetting    <- data[rows, columns]
  num_operation <- function(x, operation) {
    if (is.numeric(x)) {
      return(operation(x))
    } else {
      return(table(x))
    }
  }
  calculate <- function(subsetting, columns, operation) {
  for(i in seq_along(columns)) {
    calculate_v <- num_operation(data[rows,columns[i]], operation)
  }
    return(calculate_v)
  }
  return(list(subsetting, calculate(subsetting, columns, operation)))
}
work_with_dataset(data, 1:33, c('Tree'), mean)[[2]]
```

```{r}
data[['circumference']]
```



```{r}
work_with_dataset <- function(data, rows, columns, operation) {
  subsetting    <- data[rows, columns]
  num_operation <- function(x, operation) {
    if (is.numeric(x)) {
      return(operation(x))
    } else {
      return(table(x))
    }
  calculate <- sapply(subsetting, num_operation)
  }
  return(list(subsetting, calculate))
}
work_with_dataset(data, 1:30, c('Tree'), sd)[[1]]
```


















data = Orange
subsetting    <- data[1:30, c("age","circumference")]


v <- c("age","circumference")
calculate <- function(subsetting, v, operation) {
```{r}
data = Orange
v <- c(1)
subsetting    <- data[1:30, c("age")]
num_operation <- function(x, operation) {
  if (is.numeric(x)) {
    return(operation(x))
  } else {
    return(table(x))
  }
}
  calculate <- function(subsetting, v, operation) {
  for(i in v){
    calculate_v <- num_operation(subsetting[[i]], operation)
  }
  return(calculate_v)
}

calculate(subsetting, v, mean)
```
  
  for(i in v){
    calculate_v <- num_operation(subsetting[[i]], operation)
  }
  return(calculate_v)
}

calculate(subsetting, v, mean)


num_operation <- function(x, operation) {
  if (is.numeric(x)) {
    return(operation(x))
  } else {
    return(table(x))
  }
}
num_operation(data$age, mean)


