---
title: "HW6"
author: "MariaRomanova"
---

```{r}
library(gapminder)
library(ggplot2)
library(datasets)
library(dplyr)
```

```{r}
iris_long <- iris %>%
 transmute(Species, Part = 'Sepal', Length = Sepal.Length, Width =Sepal.Width)
iris_long1 <- iris %>%
  transmute(Species, Part = 'Petal', Length = Petal.Length, Width = Petal.Width)
iris_long <- rbind(iris_long,iris_long1)
```

```{r}
ggplot(iris_long, aes(x = Length, y = Width, color = Part)) +
  geom_point(shape = 20)
```

```{r}
year_2007 <- gapminder %>%
  filter(year==2007)
```

```{r}
options(scipen=999)
theme_set(theme_gray()) 
ggplot(year_2007, aes(x = gdpPercap, color = continent)) +
  geom_point(aes(y = lifeExp, size = pop)) 
```
```{r}
df <- aggregate(lifeExp ~ year + continent, data = gapminder, mean)
```

```{r}
ggplot(df, aes(x = year, y = lifeExp, color = continent)) +
  geom_point() +
  ylim(0, max(df$lifeExp))
```

```{r}
df <- aggregate(pop ~ year + continent, data = gapminder, sum)
```

```{r}
ggplot(df, aes(x = year, y = pop, color = continent)) +
  geom_point() + 
  geom_line() +
  scale_y_log10()
```

```{r}
df <- aggregate(gdpPercap ~ year + continent, data = gapminder, mean) 
ggplot(df, aes(x = gdpPercap,color = continent)) +
  geom_density_2d(aes(y = year)) +
  facet_grid(continent ~ .)
```


